version: '3'
services:
  fintech-account-grpc:
    build:
      context: ./fintech-account-grpc
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
      - "6566:6566"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - PORT=5003
    volumes:
      - ./fintech-account-grpc:/app
    networks:
      - backend
    depends_on:
      - fintech-postgres
  fintech-transfer-grpc:
    build:
      context: ./fintech-transfer-grpc
      dockerfile: Dockerfile
    ports:
      - "5007:5007"
      - "6567:6567"

    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - PORT=5007
    volumes:
      - ./fintech-transfer-grpc:/app
    networks:
      - backend
    depends_on:
      - fintech-postgres

  fintech-postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: fintech-db
      POSTGRES_USER: SU
      POSTGRES_PASSWORD: PWD
    ports:
      - "5437:5432"
    networks:
      - backend
networks:
  backend: